import HeadNext from "next/head";

type Props = {
  title: string;
}

const Head = ({ title }: Props) => {
  return (
    <HeadNext>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </HeadNext>
  );
}

export default Head;